name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        rustup update
        rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo check
      continue-on-error: ${{ matrix.rust == 'nightly' }}

  tests_compat:
    name: Compatibility tests
    needs: build
    strategy:
      matrix:
        version: [ 21.6.0, 20.10.5 ]

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: rustup update stable

      - name: Test on single-node EventStoreDB ${{ matrix.version }}
        run: cargo test --package eventstore --test integration single_node
        env:
          CONTAINER_IMAGE_VERSION: ${{ matrix.version }}-buster-slim
          RUST_LOG: integration=debug,eventstore=debug
          RUST_BACKTRACE: 1

      - name: Set up EventStoreDB ${{ matrix.version }} cluster with Docker Compose
        run: docker-compose up -d

      - name: Test on three-cluster-node EventStoreDB ${{ matrix.version }}
        run: |
          cargo test --package eventstore --test integration -- cluster
          docker-compose down
        env:
          CONTAINER_IMAGE_VERSION: ${{ matrix.version }}-buster-slim
          RUST_LOG: integration=debug,eventstore=debug
          RUST_BACKTRACE: 1

  tests_library:
    name: Tests library unit tests
    needs: build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: rustup update stable
    - name: Run library unit tests
      run: cargo test --lib

  linting:
    name: Linting
    needs:
      - tests_compat
      - tests_library
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        rustup update stable
        rustup component add clippy-preview
        rustup component add rustfmt
    - name: Linting
      run: cargo clippy --all-features -- -D warnings
    - name: Formatting
      run: cargo fmt -- --check
